### ISSUE TITLE
enable subfunctions in parameter_file

### ISSUE THREAD

**Issue by Fil8** [Fil8/RFInder#6]
Right now there are too many modules that are enabled. These correspond to the same class (mainly `rfi.py`):
```
rfi: 
    __helpstr: Find RFI in msfile over threshold 
    enable: true #if True this module is enabled
    bad_antenna: '[]' #list of bad antennas: for no antennas try '[]'
    polarization: 'xx' #xx, yy, xy, yx (also in CAPS)
    rms_clip: 5 #Threshold for RFI identification
    noise_measure_edges: [1.400e9, 1.420e9] #min frequency and maximum frequency where to measure average std of visibilities
    baseline_cut: 615 #Cutoff baseline lenght: <  = Short, > = Long (615m midpoint of baselines of WSRT)

time_chunks:
    __helpstr: separate visibilities in small time intervals 
    enable: true
    time_step: 10 #time chunks in minutes

spw_average:
    __helpstr: averages % of RFI in spw specified by the user  (not enabled yet)
    enable: true
    spw_width: 3 #channel width of rebinned output table [MHz]
```

instead it should be something like:

```
rfi: 
    __helpstr: Find RFI in msfile over threshold 
    enable: true #if True this module is enabled
    bad_antenna: '[]' #list of bad antennas: for no antennas try '[]'
    polarization: 'xx' #xx, yy, xy, yx (also in CAPS)
    rms_clip: 5 #Threshold for RFI identification
    noise_measure_edges: [1.400e9, 1.420e9] #min frequency and maximum frequency where to measure average std of visibilities
    baseline_cut: 615 #Cutoff baseline lenght: <  = Short, > = Long (615m midpoint of baselines of WSRT) 
    time_chunks: 
        __helpstr: separate visibilities in small time intervals 
       enable: True
       time_step: 10 #time chunks in minutes
    spw_average:
        __helpstr: averages % of RFI in spw specified by the user  (not enabled yet)
        enable: true
        spw_width: 3 #channel width of rebinned output table [MHz]
```
